version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/app

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      runas: root
    - location: scripts/cleanup.sh
      runas: root

  AfterInstall:
    - location: scripts/install.sh
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      runas: root

