version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo "Detect changes..."
      - |
        CHANGED=$(git diff --name-only HEAD~1 HEAD)

        if echo "$CHANGED" | grep '^lambda/lambda-test1/'; then
          echo "Deploy user-api"

          cd lambda/lambda-test1/

          aws cloudformation package \
            --template-file template.yaml \
            --s3-bucket lambda-artifact-bucket-123456 \
            --output-template-file packaged.yaml

          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name user-api-stack \
            --parameter-overrides Environment=dev \
            --capabilities CAPABILITY_NAMED_IAM

          cd ../../
        fi

        if echo "$CHANGED" | grep '^lambda/lambda-test2/'; then
          echo "Deploy user-api"

          cd lambda/lambda-test2/

          aws cloudformation package \
            --template-file template.yaml \
            --s3-bucket lambda-artifact-bucket-123456 \
            --output-template-file packaged.yaml

          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name user-api-stack \
            --parameter-overrides Environment=dev \
            --capabilities CAPABILITY_NAMED_IAM

          cd ../../
        fi
