version: 0.2

phases:
  build:
    commands:
      - echo "=== START DEPLOY ==="
      - pwd
      - ls -la
      - echo "Deploy lambda-test1"
      - cd lambda/lambda-test1
      - |
      - aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name lambda-test1-stack \
          --parameter-overrides Environment=dev \
          --capabilities CAPABILITY_NAMED_IAM
      - cd ../lambda-test2
      - echo "Deploy lambda-test2"
      - |
          - aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name lambda-test2-stack \
          --parameter-overrides Environment=dev \
          --capabilities CAPABILITY_NAMED_IAM
